### ISSUE TITLE
Integration to ORB_SLAM_COMMUNITY

### ISSUE THREAD

**Issue by jeremysalwen** [Mechazo11/ros2_orb_slam3#15]
Hey @Mechazo11 thanks for pointing this out to me! 

We definitely welcome contributions,  and we will probably try to merge your ROS2 node into our branch tonight!

I have also added you as a contributor on the ORB_SLAM_COMMUNITY repository (https://github.com/jeremysalwen/ORB_SLAM_COMMUNITY).

I think I would want to leave the test images in a separate repo to keep the git repo small, but otherwise I like everything you've done!

**Comment by Mechazo11** [comment]
Hi @jeremysalwen 

Thank you very much for making me a contributor to the ORB_SLAM_COMMUNITY.  I am thrilled to be a part of the team.

Let me know if there is anything I can help with the ROS 2 node merger.
