### ISSUE TITLE
Jazzy Support

### ISSUE THREAD

**Issue by DanyPell** [Mechazo11/ros2_orb_slam3#16]
It would be amazing to have this ROS2/OrbSlam3 package work for ROS2 Jazzy as well.

The original OrbSlam3 package is quite old and has a lot of compiling errors. Maybe it will be best to fork it so it can be updated accordingly.

**Comment by Mechazo11** [comment]
Hi @DanyPell 

I am closing this issue for now as there is no immediate plan to move this package to Jazzy. If I have any new updates, I will reopen this issue.

With best,
@Mechazo11
