### ISSUE TITLE
bash: install/setup.bash: No such file or directory

### ISSUE THREAD

**Issue by flipphonetwerk** [Mechazo11/ros2_orb_slam3#6]
In the monocular example, the penultimate step gives an error: bash: install/setup.bash: No such file or directory. Maybe I misunderstood something...

**Comment by Mechazo11** [comment]
Hi @flipphonetwerk can you share a screenshot of the error please? Also what hardware are you using? Hopefully we will be able to get this error sorted out.

With best,
@Mechazo11

**Comment by flipphonetwerk** [comment]
I managed to fix the error, thanks for the response!

**Comment by Mechazo11** [comment]
Hi @flipphonetwerk 
Great news. If you get a chance, could you write back on what caused the issue and how you had fixed it. May be of help to others in the future.

With best,
@Mechazo11
