### ISSUE TITLE
Running in to the following issue 

### ISSUE THREAD

**Issue by kartheekmedathati** [Mechazo11/ros2_orb_slam3#8]
CMake Error at CMakeLists.txt:167 (add_executable):
  Target "mono_node_cpp" links to target "epoxy::epoxy" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

**Comment by Mechazo11** [comment]
Hi @kartheekmedathati 

Can you post the full ```CmakeLists.txt``` file, I just checked the files posted in this repo, there is no ```epoxy::epoxy``` executable, node or internal library in this project.

**Comment by Mechazo11** [comment]
Issue closed due to lack of details. @kartheekmedathati feel free to reopen if you face additional issues
